tasks:
  - before: npm install -g npm
    init: >
      npm install &
      npm run build

ports:
  - port: 6000-6999
    onOpen: ignore

vscode:
  extensions:
    - langium.langium-vscode
    - dbaeumer.vscode-eslint
