tasks:
  - init: npm install && npm run build
    command: npm run watch

ports:
  - port: 6000-6999
    onOpen: ignore

vscode:
  extensions:
    - langium.langium-vscode
    - dbaeumer.vscode-eslint
