import { createDefaultModule, DefaultModuleContext, inject, LangiumServices, Module, PartialLangiumServices } from 'langium';
import { HelloWorldGeneratedModule } from './generated/module';
import { HelloWorldValidationRegistry, HelloWorldValidator } from './hello-world-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type HelloWorldAddedServices = {
    validation: {
        HelloWorldValidator: HelloWorldValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type HelloWorldServices = LangiumServices & HelloWorldAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const HelloWorldModule: Module<HelloWorldServices, PartialLangiumServices & HelloWorldAddedServices> = {
    validation: {
        ValidationRegistry: (injector) => new HelloWorldValidationRegistry(injector),
        HelloWorldValidator: () => new HelloWorldValidator()
    }
};

/**
 * Inject the full set of language services by merging three modules:
 *  - Langium default services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 */
export function createHelloWorldServices(context?: DefaultModuleContext): HelloWorldServices {
    return inject(
        createDefaultModule(context),
        HelloWorldGeneratedModule,
        HelloWorldModule
    );
}
