name: Build

on: push

jobs:
  build:
    name: Langium
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'
    - name: Build
      shell: bash
      run: |
        mkdir packages/cli/lib
        touch packages/cli/lib/langium.js
        npm install
        npm test --workspace=langium --workspace=langium-cli