name: langium CI

# simple approach for now: every push on every branch
on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x] # only use LTS for now

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm --version
    - run: tsc --version
    - run: npm prepare
