name: Publish

permissions:
  contents: read
  id-token: write

on:
  push:
    # Only trigger on changes to package.json files in the main and maintenance branches
    branches:
      - 'main'
      - 'maintenance/**'
    paths:
      - '**/package.json'
      # Also trigger if the publish workflow, action, or script itself is changed
      - '.github/workflows/publish.yml'
      - '.github/actions/publish/**'
      - 'scripts/publish-updated-packages.ts'
  pull_request:
    branches:
      - 'main'
      - 'maintenance/**'
    paths:
      - '**/package.json'
      - '.github/workflows/publish.yml'
      - '.github/actions/publish/**'
      - 'scripts/publish-updated-packages.ts'

jobs:
  publish:
    name: Langium Publish
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Build
        shell: bash
        run: |
          npm i -g npm
          npm ci
          npm run build:clean
          npm run langium:generate:production --workspace=langium
          npm run build

      - name: Test
        if: success() || failure()
        shell: bash
        run: npm run test

      - name: Publish
        uses: ./.github/actions/publish
        with:
          dry-run: ${{ github.event_name == 'pull_request' }}
          npm-packages: |
            packages/langium
            packages/langium-railroad
            packages/langium-cli
            packages/langium-sprotty
            packages/generator-langium
            examples/arithmetics
            examples/domainmodel
            examples/statemachine
          vscode-packages: |
            packages/langium-vscode
          vsce-token: ${{ secrets.VSCE_TOKEN }}
          ovsx-token: ${{ secrets.OVSX_TOKEN }}
